### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by johnbickmore** [tecknicaltom/AncestryCitations#1]
Read the code tried creating the attributes, no luck did not work for me :(

Do you have a step by step or a sample family tree that show it working?

PS:The Gramplet installed ok and replaced the the file as required.

**Comment by sam-m888** [comment]
@uxcq You might want to read the following related discussion.

[[Gramps-users] Gramps and Ancestry hints](https://sourceforge.net/p/gramps/mailman/message/34836294/)
- 2016-02-09 18:18:41
